version: '3'
services:
  maven-ci:
    container_name: maven-ci
    build:
      context: ./images/Maven
      dockerfile: Dockerfile
      args:
        mvn_version: 3.5.4
    image: ivozzo/maven-ci
    environment:
      IMAGE_NAME: "maven-ci"
    volumes:
    - logvolume01:/var/log
    depends_on:
      - "jenkins-master"
    command: echo "maven-ci disabled"
    networks:
      secureflow:
        aliases:
          - maven

  ant-ci:
    container_name: ant-ci
    build:
      context: ./images/Ant
      dockerfile: Dockerfile
      args:
        ant_version: 1.10.5
    image: ivozzo/ant-ci
    environment:
      IMAGE_NAME: "ant-ci"
    volumes:
    - logvolume01:/var/log
    depends_on:
      - "jenkins-master"
    command: echo "ant-ci disabled"
    networks:
      secureflow:
        aliases:
          - ant

  jenkins-master:
    container_name: jenkins-master
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    image: ivozzo/jenkins
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d
    - jenkins_home:/var/jenkins_home
    networks: 
      secureflow:
        aliases:
          - master
          - jenkins
  
  sonar:
    container_name: sonar
    image: sonarqube:lts-alpine
    

volumes:
  jenkins_home: {}
  logvolume01: {}

networks: 
  secureflow: